management:
  metrics:
    export:
      newrelic:
        enabled: false
config:
  center:
    enabled: false

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/dddtemplate"
    username: "postgres"
    password: "postgres"

  flyway:
    url: "jdbc:postgresql://localhost:5432/dddtemplate"
    user: "postgres"
    password: "postgres"

  redis:
    host: localhost #to be overwrote

  cloud:
    stream:
      kafka:
        binder:
          autoAddPartitions: false
          autoCreateTopics: true
          replicationFactor: 1
          brokers: localhost:9092